# Generated by Django 5.1.6 on 2025-03-03 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_remove_buyer_order_total_remove_buyer_status_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
