# Generated by Django 5.1.6 on 2025-03-04 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0003_remove_orderitem_order_delete_order_delete_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='product_names',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buyer',
            name='total_products',
            field=models.IntegerField(default=0),
        ),
    ]
