# Generated by Django 5.1.6 on 2025-03-04 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0007_orderitem_price_per_item_alter_order_order_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price_per_item',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
