# Generated by Django 5.1.6 on 2025-03-04 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0013_remove_order_user_buyer_email_buyer_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='user',
        ),
    ]
