# Generated by Django 5.1.6 on 2025-03-01 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default=None, unique=True, upload_to='media/slider_img')),
                ('brand_name', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
                ('discount_deal', models.CharField(choices=[('NEW ARRIVAL', 'NEW ARRIVAL'), ('HOT DEALS', 'HOT DEALS')], max_length=200)),
            ],
        ),
    ]
